### ISSUE TITLE
Waveform format standardization - identify the records to be used for benchmarking

### ISSUE THREAD

**Issue by briangow** [chorus-ai/chorus_waveform#26]
When running the benchmarking as described in #11 , it would be ideal to use a variety of waveform records. We should identify records which will stress different aspects of the waveform in a given format. Please suggest a particular record (`long_record.hea`) or attribute of a record (record with 24+ hours of signals) and mention which aspect(s) it will stress (storage size, etc.).

**Comment by tcpan** [comment]
DICOM has "a few" pre-defined waveform types.  I hope I found them all...  
12 lead ECG
General ECG
Ambulatory ECG : patient cardiac conduction system collected on the body surface, which has been acquired by an ambulatory electrocardiography (Holter) device.
General 32bit ECG

Routine Scalp Electroencephalogram
Electromyogram
Electrooculogram

Basic Audio Video Waveform
hemodynamic Waveform
Basic Cardiac Electrophysiology Waveform
Arterial Pulse Waveform
Respiratory Waveform
General Audio Waveform
Real-time Audio Waveform
Multi-channel Respiratory Waveform
Body Position Waveform

**Comment by briangow** [comment]
This was completed a while ago. The waveform suite consisted of 10 files from each of 5 databases. See these posts for more details:

- https://github.com/chorus-ai/chorus_waveform/discussions/11#discussioncomment-9225909
- https://github.com/chorus-ai/chorus_waveform/discussions/11#discussioncomment-9617032
