### ISSUE TITLE
Minimize hardware resource requirements for users when working with waveforms

### ISSUE THREAD

**Issue by briangow** [chorus-ai/chorus_waveform#78]
@jshoughtaling brought up the good point that we should be thinking about minimizing hardware resource requirements when users are working with waveforms.

**Comment by del42** [comment]
what is that mean? hardware?

**Comment by briangow** [comment]
This topic goes beyond the selection of a waveform format for CHoRUS ( https://github.com/chorus-ai/chorus_waveform/discussions/11 ) but is related. When running benchmarking across different formats we noticed that some of the formats required significant hardware resources. 

When discussing this with @bemoody , he suggested that it would be tricky to develop tests which assess this on the format itself though. A lot of resource requirements for a given format wouldn't be specific to the format specification. They could be due to the software loading unnecessary packages into memory, etc. 

A simple way to address this would be to ensure that waveforms can processed with a basic / low-resource hardware configuration.

**Comment by del42** [comment]
Do we need to layout dependencies/requirements for each format? Also OS compatibilities etc.

**Comment by briangow** [comment]
> Do we need to layout dependencies/requirements for each format? Also OS compatibilities etc.

I'm not sure but this seems like a different topic to me.

**Comment by del42** [comment]
> > what is that mean? hardware?
> 
> @del42 , not sure if I understand your question but by hardware I was referring to how much compute power, RAM, etc. is needed to process waveforms.

this is part of benchmarking already, right?

**Comment by briangow** [comment]
> this is part of benchmarking already, right?

We aren't capturing and reporting this information as far as I know.

**Comment by jshoughtaling** [comment]
@briangow, @del42, and @tcpan - putting this here for record keeping.

Based on what was just discussed, I will iteratively deploy the [chorus-waveform image](https://github.com/chorus-ai/chorus_waveform/pkgs/container/chorus-waveform) as an Azure container app with a specified resource set (vCPU & RAM), execute the [benchmarking script](https://github.com/chorus-ai/chorus_waveform/blob/fdde0140b3f8b300d8028161307f34fbe8351139/.github/workflows/benchmark.yml#L82) at each configuration, and compile the results to gauge resource constraints on the format and/or its associated software package(s). 

In parallel, @tcpan will try and extract relevant properties from the raw files with the existing workflow, and we will plan to reconvene next week.

Am I missing anything?

**Comment by briangow** [comment]
Thanks @jshoughtaling , there are only a few waveforms (out of the 50 being used for benchmarking) in the `data` directory of this repository. 

If I added all of the waveforms to a separate repository would that work with your container app or do they need to be in the chorus_waveform repo? 

@tcpan , is it ok to add the data you provided to a public repository?

**Comment by jshoughtaling** [comment]
@briangow - feel free to add them to a private repo (or share them with me in some other secure way if that's easier). Getting them into the container app shouldn't be a challenge regardless.

**Comment by del42** [comment]
> @briangow, @del42, and @tcpan - putting this here for record keeping.
> 
> Based on what was just discussed, I will iteratively deploy the [chorus-waveform image](https://github.com/chorus-ai/chorus_waveform/pkgs/container/chorus-waveform) as an Azure container app with a specified resource set (vCPU & RAM), execute the [benchmarking script](https://github.com/chorus-ai/chorus_waveform/blob/fdde0140b3f8b300d8028161307f34fbe8351139/.github/workflows/benchmark.yml#L82) at each configuration, and compile the results to gauge resource constraints on the format and/or its associated software package(s).
> 
> In parallel, @tcpan will try and extract relevant properties from the raw files with the existing workflow, and we will plan to reconvene next week.
> 
> Am I missing anything?

@jshoughtaling I don't follow how VCPU, RAM usage being collected in this scenario? How will you show per benchmarking operation? 
I would like to know how much memory loaded on, if I am asking for 500s chunk in certain offset place. I thought we are planning to benchmark peak memory detection [here](https://github.com/chorus-ai/chorus_waveform/discussions/11#discussioncomment-8647409) initially, @briangow , no?

**Comment by briangow** [comment]
@del42 , you are correct, we discussed peak memory usage and a number of other items as things to consider adding to our benchmarking tests. However, in subsequent meetings, after the initial benchmarking code was developed, we decided to move forward with the tests in the current version of the benchmarking code.

**Comment by briangow** [comment]
@jshoughtaling , ok, I'll share the files with you via a cloud bucket.

**Comment by tcpan** [comment]
I've created a pull request with update to the benchmark code that measures peak memory usage (for read and write calls).  I am also capturing the wall time, which can be compared to cpu-time to get a hint at parallelized code.

re. emory data, probably best not to release it just yet - I am not sure if the 10 test cases are in the submission set.  But they are deidentified.

**Comment by jshoughtaling** [comment]
Completed and included in report.
See #81 for code used in performance analysis.
